# -*- coding: utf-8 -*-
"""Generador de contenido Fase 2 - parte 2: personality (120 items, 13 dimensiones)."""

# Cada tupla: (dimension_code, dimension_label, [(texto, is_reverse), ...])
PERSONALITY_DIMENSIONS = [
    ("liderazgo", "Liderazgo", [
        ("Me resulta natural asumir el rol de líder cuando un grupo lo necesita.", False),
        ("Los demás suelen buscarme para que guíe decisiones importantes.", False),
        ("Disfruto inspirar a otros para que den su mejor esfuerzo.", False),
        ("Prefiero mantenerme al margen y dejar que otros lideren.", True),
        ("Me siento cómodo marcando el rumbo cuando el equipo está indeciso.", False),
        ("Evito tomar el liderazgo incluso cuando nadie más lo hace.", True),
        ("Sé transmitir una visión clara que motiva a otros a seguirme.", False),
        ("Tomo la responsabilidad de los resultados del grupo, buenos o malos.", False),
        ("Me cuesta influir en las decisiones de un grupo.", True),
        ("Cuando surge un problema en el equipo, propongo el camino a seguir.", False),
    ]),
    ("iniciativa", "Iniciativa", [
        ("Propongo mejoras sin que nadie me lo pida.", False),
        ("Actúo antes de que los problemas se vuelvan urgentes.", False),
        ("Prefiero esperar a que me digan exactamente qué hacer.", True),
        ("Busco oportunidades para aportar más allá de mis funciones.", False),
        ("Suelo dejar pasar ideas porque no quiero tomar la delantera.", True),
        ("Me adelanto a las necesidades antes de que surjan.", False),
        ("Empiezo tareas nuevas por convicción propia, no por obligación.", False),
        ("Cuando veo algo que se puede mejorar, actúo de inmediato.", False),
        ("Rara vez propongo algo si no me lo piden explícitamente.", True),
    ]),
    ("persistencia", "Persistencia", [
        ("Sigo intentando aunque los primeros resultados no sean buenos.", False),
        ("Termino lo que empiezo, incluso cuando se vuelve difícil.", False),
        ("Me doy por vencido fácilmente ante los primeros obstáculos.", True),
        ("Mantengo el esfuerzo constante hasta lograr el objetivo.", False),
        ("Cuando un proyecto se complica, tiendo a abandonarlo.", True),
        ("Insisto en encontrar una solución aunque tome mucho tiempo.", False),
        ("No me rindo aunque el camino se vuelva largo y tedioso.", False),
        ("Prefiero cambiar de actividad en cuanto algo se pone cuesta arriba.", True),
        ("Vuelvo a intentarlo las veces que sea necesario hasta conseguirlo.", False),
    ]),
    ("orientacion_logro", "Orientación al Logro", [
        ("Me fijo metas exigentes y trabajo para alcanzarlas.", False),
        ("Me motiva superar mis propios resultados anteriores.", False),
        ("Me conformo con hacer lo mínimo necesario.", True),
        ("Disfruto medir mi progreso frente a objetivos concretos.", False),
        ("No me importa mucho si mis resultados son sobresalientes o no.", True),
        ("Busco constantemente formas de mejorar mi desempeño.", False),
        ("Siento satisfacción genuina cuando logro una meta difícil.", False),
        ("Prefiero metas fáciles de alcanzar antes que metas ambiciosas.", True),
        ("Me esfuerzo más cuando el reto que enfrento es significativo.", False),
    ]),
    ("necesidad_supervision", "Necesidad de Supervisión", [
        ("Necesito que alguien revise mi trabajo con frecuencia para sentirme seguro.", False),
        ("Rindo mejor cuando tengo instrucciones detalladas paso a paso.", False),
        ("Trabajo igual de bien con o sin supervisión constante.", True),
        ("Prefiero que mi jefe apruebe cada decisión antes de avanzar.", False),
        ("Me siento cómodo tomando decisiones sin consultar a nadie.", True),
        ("Sin una guía clara, me cuesta avanzar en mis tareas.", False),
        ("Suelo pedir confirmación antes de continuar con un trabajo importante.", False),
        ("Puedo organizarme solo, sin que nadie esté verificando mi avance.", True),
        ("Me tranquiliza que alguien supervise de cerca lo que hago.", False),
    ]),
    ("sociabilidad", "Sociabilidad", [
        ("Disfruto conocer gente nueva en el trabajo.", False),
        ("Me energiza pasar tiempo conversando con mis colegas.", False),
        ("Prefiero trabajar en silencio y sin interactuar demasiado.", True),
        ("Participo activamente en actividades sociales de la empresa.", False),
        ("Me resulta agotador socializar durante la jornada laboral.", True),
        ("Entablo conversación fácilmente con personas que no conozco.", False),
        ("Busco oportunidades para relacionarme con distintas áreas de la organización.", False),
        ("Prefiero mantenerme alejado de las reuniones informales del equipo.", True),
        ("Me gusta ser parte de grupos y actividades colectivas.", False),
    ]),
    ("estabilidad_emocional", "Estabilidad Emocional", [
        ("Mantengo la calma incluso en situaciones tensas.", False),
        ("Puedo manejar las críticas sin que afecten mi estado de ánimo por mucho tiempo.", False),
        ("Me altero con facilidad ante los imprevistos.", True),
        ("Recupero mi equilibrio emocional rápido después de un mal momento.", False),
        ("Los cambios inesperados me generan ansiedad considerable.", True),
        ("Enfrento los problemas con serenidad, sin dramatizar.", False),
        ("Las presiones del trabajo rara vez me hacen perder la compostura.", False),
        ("Puedo tomar decisiones con la cabeza fría incluso bajo estrés.", False),
        ("Suelo preocuparme en exceso por cosas que aún no han pasado.", True),
    ]),
    ("comunicacion", "Comunicación", [
        ("Expreso mis ideas de forma clara y ordenada.", False),
        ("Me aseguro de que mi mensaje se entienda antes de terminar de hablar.", False),
        ("Me cuesta poner en palabras lo que pienso.", True),
        ("Adapto mi forma de comunicar según la persona que tengo enfrente.", False),
        ("Suelo dar explicaciones confusas o desordenadas.", True),
        ("Escucho activamente antes de responder en una conversación.", False),
        ("Soy capaz de explicar temas complejos de forma sencilla.", False),
        ("Prefiero evitar dar explicaciones y esperar que los demás entiendan solos.", True),
        ("Me comunico con seguridad tanto en grupos pequeños como grandes.", False),
    ]),
    ("adaptabilidad", "Adaptabilidad", [
        ("Me ajusto con facilidad a cambios repentinos en mis tareas.", False),
        ("Encuentro nuevas formas de trabajar cuando las condiciones cambian.", False),
        ("Me cuesta mucho salir de mi forma habitual de hacer las cosas.", True),
        ("Me adapto bien a distintos estilos de trabajo y de personas.", False),
        ("Los cambios de planes de último momento me desestabilizan por completo.", True),
        ("Veo el cambio como una oportunidad más que como una amenaza.", False),
        ("Puedo cambiar de estrategia rápido si la actual no está funcionando.", False),
        ("Prefiero que todo se mantenga exactamente igual siempre.", True),
        ("Me adapto con facilidad a nuevas herramientas o tecnologías.", False),
    ]),
    ("apego_normas", "Apego a Normas", [
        ("Sigo cuidadosamente las políticas y procedimientos de mi empresa.", False),
        ("Considero importante respetar las reglas aunque no esté de acuerdo con todas.", False),
        ("Suelo saltarme procedimientos si me parecen poco prácticos.", True),
        ("Cumplo los lineamientos establecidos incluso cuando nadie los está revisando.", False),
        ("Prefiero encontrar atajos aunque no sigan el proceso oficial.", True),
        ("Me tomo en serio las normas de seguridad y calidad.", False),
        ("Documento mi trabajo según los estándares definidos por la organización.", False),
        ("Ajusto las reglas a mi conveniencia cuando creo que nadie se dará cuenta.", True),
        ("Respeto los protocolos aunque impliquen invertir más tiempo de trabajo.", False),
    ]),
    ("responsabilidad", "Responsabilidad", [
        ("Cumplo mis compromisos laborales sin necesidad de recordatorios.", False),
        ("Me hago cargo de mis errores en lugar de buscar excusas.", False),
        ("A veces dejo tareas pendientes sin avisar a nadie.", True),
        ("Entrego mi trabajo en los tiempos acordados.", False),
        ("Suelo justificar mis fallas culpando a otros.", True),
        ("Cuido los recursos de la empresa como si fueran propios.", False),
        ("Asumo las consecuencias de mis decisiones, sean buenas o malas.", False),
        ("Con frecuencia llego tarde a mis compromisos laborales.", True),
        ("Cumplo mi palabra incluso cuando resulta incómodo.", False),
        ("Reviso mi propio trabajo para asegurarme de que cumple lo prometido.", False),
    ]),
    ("independencia", "Independencia", [
        ("Prefiero resolver los problemas por mí mismo antes de pedir ayuda.", False),
        ("Tomo decisiones basadas en mi propio criterio.", False),
        ("Necesito la aprobación de otros para sentirme seguro de mis decisiones.", True),
        ("Me organizo bien sin depender de instrucciones constantes.", False),
        ("Sigo la opinión de la mayoría aunque no esté de acuerdo con ella.", True),
        ("Confío en mi propio juicio para actuar en situaciones ambiguas.", False),
        ("Defiendo mi punto de vista incluso si no es el más popular.", False),
        ("Me cuesta actuar si no tengo el visto bueno de alguien más.", True),
        ("Prefiero trazar mi propio camino en lugar de seguir el de otros.", False),
    ]),
    ("orientacion_equipo", "Orientación al Trabajo en Equipo", [
        ("Colaboro activamente para alcanzar los objetivos comunes del equipo.", False),
        ("Comparto información relevante con mis compañeros sin que me la pidan.", False),
        ("Prefiero trabajar solo aunque el proyecto requiera colaboración.", True),
        ("Celebro los logros del equipo tanto como los míos propios.", False),
        ("Me cuesta confiar en el trabajo que hacen otras personas.", True),
        ("Ayudo a mis compañeros aunque no sea parte directa de mi tarea.", False),
        ("Considero las ideas de otros aunque sean distintas a las mías.", False),
        ("Prefiero que el mérito de un logro grupal sea solo mío.", True),
        ("Me adapto a los roles que el equipo necesita en cada momento.", False),
        ("Busco activamente la opinión de mis compañeros antes de decidir algo que los afecta.", False),
    ]),
]

PERSONALITY_TOTAL = sum(len(v[2]) for v in PERSONALITY_DIMENSIONS)
assert PERSONALITY_TOTAL == 120, PERSONALITY_TOTAL
